export const OSV_ADVISORY_RESULT_LIMIT = 1_500_000;
export const OSV_ADVISORY_BATCH_LIMIT = 12;

export const OSV_ECOSYSTEMS = [
  "AlmaLinux",
  "Alpaquita",
  "Alpine",
  "Android",
  "Azure Linux",
  "BellSoft Hardened Containers",
  "Bioconductor",
  "Bitnami",
  "Chainguard",
  "CleanStart",
  "ConanCenter",
  "CRAN",
  "crates.io",
  "Debian",
  "Docker Hardened Images",
  "Echo",
  "FreeBSD",
  "GHC",
  "GitHub Actions",
  "Go",
  "Hackage",
  "Hex",
  "Julia",
  "Kubernetes",
  "Linux",
  "Mageia",
  "Maven",
  "MinimOS",
  "npm",
  "NuGet",
  "opam",
  "openEuler",
  "openSUSE",
  "OSS-Fuzz",
  "Packagist",
  "Photon OS",
  "Pub",
  "PyPI",
  "Red Hat",
  "Rocky Linux",
  "Root",
  "RubyGems",
  "SUSE",
  "SwiftURL",
  "TuxCare",
  "Ubuntu",
  "vcpkg",
  "VSCode",
  "Wolfi",
  "GIT",
] as const;
